### ISSUE TITLE
Give gem authors admin write access to the repository

### ISSUE THREAD

**Issue by bumi** [railslove/epics#108]
It seems that @railslove removed the authors of this gem from the repository - probably by accident.
Sadly nobody @railslove takes care of the maintenance of the gem and has abandoned it.

Please at least transfer ownership of this repository to one of the gem authors. 

//cc @tmschndr @stephanpavlovic @bonflintstone

**Comment by bonflintstone** [comment]
You are right, it should not be like this! I think this happened in some well meant cleanup of our Github organisation. Can you give me a list of people that should have access to this repository @bumi? If anyone feel up to the task of overtaking this project I am also more than happy to facilitate the transfer.

At Railslove we simply do not have the expertise to mainting this project anymore, so we are more than happy to pass this on! Thanks for bringing this up.

**Comment by bonflintstone** [comment]
Alright, you all god write access now. I think it's a good idea to create a new organization, though I think for now it should also be ok for this to stay here until someone wants to put in the effort to set it up. If other people need to be added or some other things changed, just ping me.

**Comment by bumi** [comment]
thanks!!

**Comment by bumi** [comment]
hmm. still looks I am missing: 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/318/137596446-10947030-f5d0-4c47-ab37-6880e3ee5b32.png">

**Comment by bumi** [comment]
I think we have to remove it?

**Comment by kangguru** [comment]
looks like https://cla-assistant.io/ is now a thing

**Comment by tobischo** [comment]
Are there any updates on this?

I'd say if a CLA is required by railslove to be safe when it comes to accepting contributions, then someone from railslove should set it up. It would be much appreciated if that could happen sooner rather than later, as that appears to be blocking all current and potential future contributions.

Additionally it would allow us to more easily carry on with our gained collaborator permissions and deal with incoming issues.

**Comment by tobischo** [comment]
Happy new year everyone!

Just so that this doesn't get lost here: any updates on this?

**Comment by zollillo** [comment]
Hi and happy new year!

It's on our ToDos here at Railslove and we'll give an update soon.
Awfully sorry that this takes so long!

**Comment by zollillo** [comment]
Hi @bumi, @tobischo and @kangguru,

we removed `clahub` and replaced it with [cla-assistant.io](https://github.com/cla-assistant/cla-assistant) since handling CLAs is still required.

Again, sorry for taking so long!

**Comment by tobischo** [comment]
Hi @zollillo Excellent, thanks I signed it already so my changes should be good to go

**Comment by tobischo** [comment]
@zollillo @bumi @kangguru 
How are we going to deal with gem releases of new versions?

Also to raise it here: do we have to maintain the JRuby support?
I am having issues getting that to work (lack of experience with JRuby really) and would rather remove it than being stuck maintaining that bit.

**Comment by bumi** [comment]
I'd be fine with removing JRuby. If somebody needs it maybe they can then contribute and work on those tests? 

@kangguru are you ready to do a new release (now with #105 ) ?

**Comment by tobischo** [comment]
Closing this issue now, as the original purpose was achieved.
Waiting for a renewed invite to be rubygems maintainer, as I missed it previously (sorry about that)
