### ISSUE TITLE
EMSA-PSS sign 

### ISSUE THREAD

**Issue by andrew-svirin** [railslove/epics#120]
Hello,

Maybe someone can help me with PHP analog of client.

Is this script https://github.com/railslove/epics/blob/c1b9167b0f1daf076075164b7eb36b66c85ca3fb/lib/epics/key.rb#L32
Is the same that?:
```php
        $rsa = new \phpseclib\Crypt\RSA();
        $rsa->setPassword($password);
        $rsa->loadKey($privateKey, \phpseclib\Crypt\RSA::PRIVATE_FORMAT_PKCS1);
        $rsa->setHash('sha256');
        $rsa->setMGFHash('sha256');
        $rsa->setSignatureMode(\phpseclib\Crypt\RSA::SIGNATURE_PSS);
        $sign = $rsa->sign($data);
```

**Comment by tobischo** [comment]
The better comparison is probably the adaption you can find in #105 where the implementation from epics is replaced with one from openssl.

According to https://stackoverflow.com/questions/8469909/is-there-any-way-to-generate-pss-padded-signatures-in-php and https://hotexamples.com/examples/phpseclib.crypt/RSA/sign/php-rsa-sign-method-examples.html your approach should be the equivalent.

**Comment by andrew-svirin** [comment]
@tobischo okay, Thank you!
Yes, private key is password protected.
