### ISSUE TITLE
Add @tobischo as Gem author and allow publishing to rubygems

### ISSUE THREAD

**Issue by bumi** [railslove/epics#134]
@tobischo is currently mainly maintaining this library and has done great work in pushing it forward. 
He should get access to the Rubygems project to be able to release the long awaited version 2.0

**Comment by bumi** [comment]
cc @uepsilon

**Comment by tobischo** [comment]
Thank you for the vote of confidence

It would also be fine for me if someone from railslove would be available to do that every now and again.

**Comment by bumi** [comment]
Sadly this seems problematic, guess everybody is busy. So I think we should put this in more hands.

**Comment by tobischo** [comment]
Any news here?

**Comment by kangguru** [comment]
check you 📬 @tobischo

**Comment by tobischo** [comment]
Sorry, but this was not at the top of my mind in the last few days and the link has expired.

Could you please trigger it again? @kangguru

**Comment by kangguru** [comment]
@tobischo sorry :) on mine neither, please check your inbox

**Comment by tobischo** [comment]
Thank you, now I didn't miss the mail 😄
