### ISSUE TITLE
EBICS version support

### ISSUE THREAD

**Issue by frantisekrokusek** [railslove/epics#139]
Hi team,

Thanks again for this amazing gem.

Can you please specify in you documentation which version of EBICS do this library support ? (1.1, 2.4.2, 3.0 ????)

Thanks

**Comment by tobischo** [comment]
It should be ebics 2.5

**Comment by frantisekrokusek** [comment]
Thanks a lot.
Any ways it might support 3.0 somehow ?

**Comment by tobischo** [comment]
Not without significant effort in adding support for it.

The documentation is really not very developer friendly unless you are very used to banking standard documentations (at least to me) which I am not.

If you somehow have the chance, I would avoid using EBICS and ask the bank in question whether they have something more modern

**Comment by frantisekrokusek** [comment]
Oh yeah the whole banking system is built on unclear, shady stuff... That's why they make so much money out of it.

**Comment by frantisekrokusek** [comment]
Can we at least specify the version in the README ?

**Comment by tobischo** [comment]
https://github.com/railslove/epics/commit/926cb2c81c4b2779582db915da499e4ec5dba8a6
