### ISSUE TITLE
EBICS_AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by deepthi564** [railslove/epics#145]
Hi Team,

Thank you so much for having this product developed, this was very helpful for generating the ini letter for the bank. 
Now Im trying to send a HPB request and it throws below error, any idea what is this related to? The bank has already confirmed that the User is now Initialised

in `block in call': EBICS_AUTHENTICATION_FAILED - Authentication signature error (Epics::Error::TechnicalError)

**Comment by deepthi564** [comment]
This Issue is resolved by setting up the client again along with Key initiated while creating the INI Letter, Thank you.

**Comment by tobischo** [comment]
Happy to see that you managed to find the help in the documentation 👍 
Closing this issue then
