### ISSUE TITLE
C54 and Z54 question

### ISSUE THREAD

**Issue by mauricelehmann** [railslove/epics#149]
Hello team ! 
We are looking for a ebics client for our rails infrastructure, and we came across your gem. Although we are not sure if we'll manage to make it work for our needs : getting the daily camt054 file from a swiss bank.
As we understand, our bank (PostFinance in Switzerland) recommand to use the **Z54** order type, and we saw that you only implement the **C54** order type. We'll ask the bank if this order can also work (you have maybe the answer too?), but in the meantime, do you think it could be a legitimate / planned feature to add ?  

Thank for your time !

**Comment by mauricelehmann** [comment]
>I could prepare a pull request with Z54. Would you be willing to test it with your bank based on the feature branch before I would be merging and releasing it?

@tobischo sure! Although we didn't decide yet what solution we will take, i can surely try the feature, since we already have the login ids & keys for it :)

**Comment by tobischo** [comment]
Alright, addressed it in #150. The change right now makes the assumption that it is pretty much identical to C54.
Happy testing and let me know whether this works.

**Comment by tobischo** [comment]
Inspired by #151, which would be pending for the contributor license agreement, I also added Z52 and Z53 in #150 - which makes sense, as they are similar/kind of related

**Comment by andre-m-dev** [comment]
@mauricelehmann and @tobischo perhaps you are interested in making further adjustments for Switzerland together. We are currently working on a connection to the ZKB (retrieval of account data and credit transfer, preferably also for QR IBAN's)

**Comment by tobischo** [comment]
I just used https://iso20022test.credit-suisse.com to verify that the general order types should be ok for Z52,Z53 and Z54.

They don't have any data available, but accepted the order type, so I would assume that it is fine.

@andre-m-dev If it is something that can be retrieved through EBICS, then it might have a place in epics. Feel free to create an issue here in github to discuss some other features that you might be looking for.

**Comment by tobischo** [comment]
Z52, Z53 and Z54 are released in v2.3.0

For any other changes or bugs, please feel free to open new issues

**Comment by mauricelehmann** [comment]
@tobischo sorry, didn't manage make the setup and test it in time, because i’m a little bit confused about the setup process: 
I managed to call the Epics::Client.setup and save_keys, with the infos from the letter we received from our bank (PostFinance) (partner id, user id, host url etc)
But, in the letter, we also got their E002 and X002 keys.
And i don’t understand where or when should i use those in the setup process… 
I read in their instructions that i should use the keys in the setup, along with the host id etc… , but they assume we use a dedicated software or something… 
Any idea?

**Comment by tobischo** [comment]
Hi @mauricelehmann, yes, correct. The purpose of this gem is just the communication layer, not necessarily the specific file format layer. The one exception to that is I guess that zip file responses from the ebics server are unpacked automatically.

In terms of parsing it, you could take some inspiration from this gem: https://github.com/viafintech/sepa_file_parser/ and e.g. fork it or take a similar approach. And if you need specific changes made for it, we can have the discussion on that repo. I am sure we could add the specific XML formats, even if they are not strictly speaking SEPA
