### ISSUE TITLE
Server Port different than 80/443?

### ISSUE THREAD

**Issue by dmoac** [railslove/epics#156]
Hello!

Anyone was able to use the gem and do a setup with a different server port than the standard 80/443? We need to use the server port 4500.

Suggestions?

Thank you!

**Comment by tobischo** [comment]
Hi @dmoac,
I am not currently near a computer to test options.
Could you show examples of what you have tried that hasn't worked so far?

The client uses Faraday, so anything that works there should work to pass the port.

**Comment by tobischo** [comment]
Yeah, so after taking a look at faraday specifically, I am seeing no reason why this shouldn't work.

You would specify the port as part of the URL as per usual with e.g. https://your-ebics-server.com:4500/path.

**Comment by dmoac** [comment]
@tobischo - Hey! Thanks for the analysis!

Probably I wasn't doing something correct on my side before - now it seems only a problem of the Bank firewall configuration

```
irb(main):031:0> user.INI
/Users/dmoac/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/net/http.rb:1603:in `initialize': Failed to open TCP connection to mbank.ebicsdomain.com:4500 (execution expired) (Faraday::ConnectionFailed)
/Users/dmoac/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/net/http.rb:1603:in `initialize': Failed to open TCP connection to mbank.ebicsdomain.com:4500 (execution expired) (Net::OpenTimeout)
irb(main):032:0>
```

Will post you updated if yes or no after firewall configuration is up-to-date!

Thanks!
