### ISSUE TITLE
Support for multi-segment responses

### ISSUE THREAD

**Issue by klausmeyer** [railslove/epics#18]
Hi,

I noticed during the development of a `C54` feature (basically a copy of your `C53` implementation) that the multi segment responses aren't supported currently (also seen your comment in https://github.com/railslove/epics/commit/468fa7cf13a1c7fd53e67f19f1e75464c6532af8).

Are you already working on the support for multipart responses or do you have any plans for it?
I may also be able to contribute some code if it makes sense.

Cheers, Klaus

**Comment by kangguru** [comment]
hej,

woopsie :) a well, i though i covered all the `Cxx` order types. 

if you could contribute the multi-segment code, that'd be awesome. let me know if i can support you somehow, the main reason it's missing right now, was the lack of real sample data :)

**Comment by klausmeyer** [comment]
Just wanted to give a short update: I managed some weeks ago to fetch the segmented data from our account at deutsche bank but then stuck on correctly decrypting and unzipping the data afterwards. 

Currently I don't have enough spare time to get it further.

Maybe I can already create a PR for the `C54` part and push a branch with my current status on the segmented fetch logic so you could also take a look at it and maybe contribute with your experience of the EBICS protocol.

**Comment by kangguru** [comment]
yeah, thanks for the update. 

go ahead for a C54 PR, i'm also interested in the segment code.

**Comment by klausmeyer** [comment]
Fine. I've created a PR for the `C54` message: #20 and also pushed my WIP on the multisegment topic: https://github.com/railslove/epics/compare/master...klausmeyer:multi-segment-response-support

**Comment by jegan-maker** [comment]
Finally we fixed and test c53 multi-segment issue and I have raised [Fix for multi-segment issue by jegan-maker · Pull Request #172 · railslove/epics](https://github.com/railslove/epics/pull/172)
as well review and approve and let me know once the new version is published.. This changes tested

**Comment by tobischo** [comment]
Unfortunately you still have not signed the contributer license agreement @jegan-maker 

Therefore nothing much sense in reviewing the changes, as they would not be mergeable
