### ISSUE TITLE
C53 returns "unclean" data

### ISSUE THREAD

**Issue by MMore** [railslove/epics#24]
Hi,

we just found your nice gem. So we tried downloading account statements using C53.

```ruby
e = Epics::Client.new(key, "secret", "https://server", "a", "b", "c")
c53 = e.C53(Date.today.prev_day(2), Date.today.prev_day)
puts c53
```

That's the output (of course I wiped out some data):

    PK?F?ఁ?
    ?
    42015-07-24_C53_EUR_13.xml<?xml version='1.0' encoding='UTF-8' ?><Document xmlns='urn:iso:std:iso:20022:tech:xsd:camt.053.001.02'>WIPED OUT</Document>PK??F?ఁ?
    ?
    42015-07-24_C53_EUR_13.xmlPKb

Is it an issue with our bank? Can you verify that C53 works for you?

**Comment by kangguru** [comment]
oh dear! thx for using the gem, i'll fix the issue, stay tuned :)

**Comment by kangguru** [comment]
@MMore could you please try the current master if it now gives you more reasonable results. it should be an array containing multiple xml strings

**Comment by MMore** [comment]
I guessed that the file is still compressed. Thanks, this fixes the issue! Expecting the next release :)

**Comment by kangguru** [comment]
alright. thx for testing it out.

will roll a new release latest on monday

**Comment by kangguru** [comment]
sry, i took me quite while but 1.3.0 just hit the road!
