### ISSUE TITLE
CCT does not transfer the SEPA file

### ISSUE THREAD

**Issue by manoveg** [railslove/epics#25]
Hi,

I was trying to transfer the sepa file but it's not working with Sparkasse Wuppertal and Sparkasse Pforzheim

I did
e = Epics::Client.new(key, secret, server, a, b, c)
e.HPB
e.CCT("sepa.xml")

Bank replied that they received an error message in their system that corrupt file is received however file is not received. The Sepa.xml is verified separately and checked by the bank to be correct.

Please suggest.

**Comment by kangguru** [comment]
please make sure you're actually transferring the XML content and not the file name (as your code suggests). Every upload-method will take the plain contents for the file and will not try to read a file.

i've also updated the readme to make this point clearer.

does this solve your issue?

**Comment by manoveg** [comment]
Hi,
thanks this issue is solved. I am facing another problem.
the message from the bank now is 
"keine Unterschriftberechtigung"
"Sie senden uns die Datei mit einer autorisierten elektronischen Unterschrift. Dies ist aufgrund der reinen Transportberechtigung nicht zulässig"

The account with the bank has Unterschriftsklasse T

Please advice.

**Comment by kangguru** [comment]
@manoveg could you please check if the issue persists when you change the following line

https://github.com/railslove/epics/blob/master/lib/epics/cct.rb#L18

from `OZHNN` to `DZHNN `

**Comment by manoveg** [comment]
Hi Lars,

thanks for your mail and apologies for late reply.
Unfortunately I could not get a chance to try this yet

On Thu, Aug 6, 2015 at 5:18 PM, Lars <notifications@github.com> wrote:

> @manoveg <https://github.com/manoveg> could you please check if the issue
> persists when you change the following line
>
> https://github.com/railslove/epics/blob/master/lib/epics/cct.rb#L18
>
> from OZHNN to DZHNN
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railslove/epics/issues/25#issuecomment-128408278>.
>



-- 
Thanks & regards,
Manoveg Saxena

No trees were killed to send this message, but a large number of electrons
were terribly inconvenienced.

**Comment by manoveg** [comment]
Hi Lars,

thanks for your mail and apologies for late reply.
Unfortunately I could not get a chance to try this yet as I am travelling
this week.
I will try this asap next week and will get back to you with the feedback.

Thanks & regards,
Manoveg

On Tue, Aug 11, 2015 at 11:06 PM, Manoveg Saxena <manoveg@gmail.com> wrote:

> Hi Lars,
>
> thanks for your mail and apologies for late reply.
> Unfortunately I could not get a chance to try this yet
>
> On Thu, Aug 6, 2015 at 5:18 PM, Lars <notifications@github.com> wrote:
>
>> @manoveg <https://github.com/manoveg> could you please check if the
>> issue persists when you change the following line
>>
>> https://github.com/railslove/epics/blob/master/lib/epics/cct.rb#L18
>>
>> from OZHNN to DZHNN
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/railslove/epics/issues/25#issuecomment-128408278>.
>>
>
>
>
> --
> Thanks & regards,
> Manoveg Saxena
>
> No trees were killed to send this message, but a large number of electrons
> were terribly inconvenienced.
>



-- 
Thanks & regards,
Manoveg Saxena

No trees were killed to send this message, but a large number of electrons
were terribly inconvenienced.

**Comment by justjamesdev** [comment]
5 years later.. Did you solve this problem?! I have the same error! haha

**Comment by bumi** [comment]
@justjamesdev do you have more context and code of what you are trying to do?

**Comment by justjamesdev** [comment]
Hey, It turns out, the account did not actually have permission to send! The error was quite truthful!

**Comment by bumi** [comment]
ah, great. :) good to hear you got it working!
