### ISSUE TITLE
Is EBICS_NO_DOWNLOAD_DATA_AVAILABLE really an error?

### ISSUE THREAD

**Issue by namxam** [railslove/epics#40]
I would vote to handle the case of no available statements differently. It should not raise an error, but return an empty array. We could catch the exception.

**Comment by bumi** [comment]
do you have some more context around EBICS_NO_DOWNLOAD_DATA_AVAILABLE. When does that error happen?

**Comment by bumi** [comment]
ping @namxam any thoughts? 

and maybe we should do some voting @kangguru @yoyostile :+1: or :-1:

**Comment by bumi** [comment]
problem would be that it changes the behavior. so if we decide to use this it should probably go in the next major release?

**Comment by bumi** [comment]
no vote == closing the issue until somebody opens it again to request this change.
