### ISSUE TITLE
EBICS_ONLY_X509_SUPPORT

### ISSUE THREAD

**Issue by tomaskulich** [railslove/epics#43]
After invoking INI request to the bank I try integrate with, I got 'EBICS_ONLY_X509_SUPPORT' error message. Although this is one of the standard error codes, I'm not sure what does it mean and how to fix it? I'll be more than happy for any clues about this.

**Comment by kangguru** [comment]
can you provide the institute that you're trying to connect to? is it by any chance a french bank?

**Comment by tomaskulich** [comment]
Hi, how do you know? Yes, it is a French bank: http://www.arkea.com/

**Comment by kangguru** [comment]
X.509 is mostly used by french banks, so i just made an educated guess :)

Unfortunately epics hasn't got support for X.509 mainly because we lack access to bank accounts that feature this kind of authentication.

**Comment by tomaskulich** [comment]
Thank you for the information!
