### ISSUE TITLE
Support for latest OpenSSL version

### ISSUE THREAD

**Issue by bumi** [railslove/epics#47]
OpenSSL changed the API and the `n=` accessors are no longer available and `set_key` must now be used. 
I guess we have to check if `set_key` is defined and then use that new API otherwise the old. 

See:
https://github.com/ruby/openssl/commit/7ea72f1f50849ad0c36e08c0ac70bbdba1d96169#diff-915017dbfe6a2e8cd9741502cfe8f759
https://github.com/nov/json-jwt/commit/aa09a07e4b3939d7a9025ba9db97a861dc0c0817#diff-e64230ecda134ae0f937388155746d86R102

**Comment by kangguru** [comment]
closed via #49
