### ISSUE TITLE
faraday dependency unbounded version constraint

### ISSUE THREAD

**Issue by ddmler** [railslove/epics#75]
Hi,
faraday has released version 1.0 a few days ago. Since then a new installation of epics is not working anymore because of breaking changes in faraday.
It seems to be related to the changes of #73

**Comment by bumi** [comment]
thanks for reporting.
can you describe "not working" for you  - installation already fails when you do `gem install epics`?

**Comment by bumi** [comment]
@kangguru @Uepsilon do you want to have a quick look at #76 and [faraday/upgrading.md](https://github.com/lostisland/faraday/blob/master/UPGRADING.md) - I think #73 solved any issue but is not released yet 
maybe you can push a release then? :shipit: :shipit: :shipit:

**Comment by Uepsilon** [comment]
@bumi I've been digging into this and since Faraday 1.0 supports ruby 2.4+ I'd bump the min. ruby version for epics to 2.4 too. Any concerns regarding that?

**Comment by Uepsilon** [comment]
I've created #82 to tackle tihs

**Comment by Uepsilon** [comment]
this has been merged! 🎉
