### ISSUE TITLE
epics CDZ implementation: wrong order type action ?

### ISSUE THREAD

**Issue by rocksit** [railslove/epics#90]
Hello epics community,

I ask my self, if the impementation of ebics ordertype CDZ [(cdz.rb)](https://github.com/railslove/epics/blob/master/lib/epics/cdz.rb) has undergone an error. Reading the [ebics compendium](https://www.ppi.de/fileadmin/user_upload/Software-Produkte/Publikationen/2018-03-23_EBICS_3.0_Kompendium_V6_D6.pdf), the order type should provide "Payment Status Report for Direct Debit". In my understanding this means an action type client "download" from ebics bank server. 
But epics client.rb

`def CDZ(document)
    upload(Epics::CDZ, document)
  end`

 implements an upload from client to bank. Is this correct ? 
If so, could someone point out, why ?

regards,
Peter

**Comment by bumi** [comment]
Sorry @rocksit I am currently not using or working on epics and it has been a while. :( So I don't know. 
But it would be great if you can share your findings for others (or if there is an error make a PR?)

**Comment by tobischo** [comment]
Semantically download would make more sense similar to e.g. C53 or CRZ.
An example for an implementation of CRZ can be found in #100

**Comment by tobischo** [comment]
Merged now - not sure when we can get a release done though

**Comment by bumi** [comment]
what is needed for the release? I can help with pinging people if needed.

**Comment by tobischo** [comment]
Basically we'd have to decide on a version, update the changelog and then someone has to publish the gem to be there.

I can prepare that and I believe because of the changes from #105 we wanted to go for a major version bump. So next up would be 2.0

**Comment by tobischo** [comment]
See #131 for prepared version bump
